feat: improve readme

diff --git a/install.conf.yaml b/install.conf.yaml
--- a/install.conf.yaml
+++ b/install.conf.yaml
@@ -34,9 +34,12 @@
 
 - shell:
     - command: |
-        if command -v darwin-rebuild >/dev/null 2>&1; then
+        if ! command -v nix >/dev/null 2>&1; then
+          echo "nix not found, skipping switch..."
+        elif command -v darwin-rebuild >/dev/null 2>&1; then
           sudo darwin-rebuild switch --flake ~/.config/nix-darwin
         else
+          echo "first time running, switching with nix..."
           sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake ~/.config/nix-darwin
         fi
       description: build and switch to the nix-darwin configuration
